# Generated by Django 5.1 on 2026-01-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_twofactorauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="address",
            field=models.TextField(blank=True, help_text="Complete business address"),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="business_hours_end",
            field=models.TimeField(blank=True, help_text="Closing time", null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="business_hours_start",
            field=models.TimeField(blank=True, help_text="Opening time", null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="country",
            field=models.CharField(blank=True, help_text="Country", max_length=100),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="district",
            field=models.CharField(blank=True, help_text="District", max_length=100),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="state",
            field=models.CharField(
                blank=True, help_text="State/Province", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="town",
            field=models.CharField(blank=True, help_text="Town/City", max_length=100),
        ),
    ]
